export default {
    TITLE_HREF: 'TITLE_HREF',
    PURCHASE_SUM: 'PURCHASE_SUM',
    MAIN_PAPER_DEPTH: 'MAIN_PAPER_DEPTH',
    CHANGE_TITLE:'CHANGE_TITLE',
    ROW_STATE: 'ROW_STATE',
    ACTIVE_MENU: 'ACTIVE_MENU',
    TOGGLE_MENU: 'TOGGLE_MENU'
};